export const LIGHT_THEME = "light";
export const DARK_THEME = "dark";

export const projects = [
  {
    id: 1,
    title: "Portfolio Website",
    description:
      "Showcase of my projects, skills, and experience as a developer",
    technologies: [
      "Next.js",
      "React.js",
      "react-spring",
      "Framer Motion",
      "Styled Components",
      "Lucide-react",
      "react-intersection-observer",
    ],
    category: "Front end",
    year: "2025",
    status: "Live",
    metrics: { users: "More than 1", conversion: "Good", performance: "90" },
    link: "https://github.com/username/neural-ecommerce",
    demo: "https://neural-ecommerce-demo.com",
    color: "#ff6b35",
  },
  {
    id: 2,
    title: "Flipkart Clone",
    description:
      "E-commerce platform with real-time collaboration and advanced search capabilities",
    technologies: [
      "React.js",
      "Node.js",
      "Express.js",
      "GraphQL",
      "MongoDB",
      "Netlify",
      "Heroku",
    ],
    category: "SaaS",
    year: "2021",
    status: "Beta",
    metrics: {
      teams: "My friends",
      efficiency: "70%",
      uptime: "Whenever we needed",
    },
    link: "https://github.com/username/quantum-tasks",
    demo: "https://quantum-tasks-demo.com",
    color: "#4ecdc4",
  },
  {
    id: 3,
    title: "Music Streaming",
    description: "Music streaming platform with personalized playlists",
    technologies: [
      "React.js",
      "next.js",
      "Redux",
      "bootstrap",
      "axios",
      "react-bootstrap",
      "sass",
      "axios",
      "styled-components",
    ],
    category: "SaaS",
    year: "2023",
    status: "beta",
    metrics: { accuracy: "90%", data: "Static", version: "4" },
    link: "https://github.com/username/climate-analytics",
    demo: "https://climate-analytics-demo.com",
    color: "#45b7d1",
  },
  {
    id: 4,
    title: "Planner",
    description:
      "Decentralized task planner without internet to remember tasks",
    technologies: ["HTML", "CSS", "JavaScript"],
    category: "SaaS",
    year: "2023",
    status: "Live",
    metrics: { accuracy: "99%", data: "Local", version: "2" },
    link: "https://github.com/username/blockchain-portfolio",
    demo: "https://blockchain-portfolio-demo.com",
    color: "#f39c12",
  },
];
